- name: General Config
  gather_facts: no
  hosts: all

  tasks:
    - name: Command
      ignore_errors: yes
      ignore_unreachable: yes
      ios_config:
        lines:
        - logging buffered 604800 warning
        - no aaa new-model
        - service timestamps debug datetime msec localtime show-timezone year
        - service timestamps log datetime msec localtime show-timezone year
        - clock timezone CET 1 0
        - clock summer-time CEST recurring last Sun Mar 2:00 last Sun Oct 3:00
        - ip dhcp snooping vlan 1-4094
        - no ip dhcp snooping information option
        - vtp mode transparent
        - spanning-tree mode rapid-pvst
        - spanning-tree extend system-id
      ios_config:
        lines:
        - logging synchronous
        parents: line con 0
