---
- name: Manage Snapshots
  hosts: all
  serial: 1
  gather_facts: false
  tasks:
    - name: delete Snapshot
      vmware_guest_snapshot:
       datacenter: Datacenter
       folder: /
       # Name im Vcenter muss Namen im AWX entsprechen!
       name: '{{ inventory_hostname }}'
       state: absent
       snapshot_name: ansible_snap_update
      delegate_to: localhost
